In [11]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [12]:
pip install -U imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [13]:
import pandas as pd
df = pd.read_csv('creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [14]:
df.shape

(284807, 31)

In [3]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
df.isnull().count()

Time      284807
V1        284807
V2        284807
V3        284807
V4        284807
V5        284807
V6        284807
V7        284807
V8        284807
V9        284807
V10       284807
V11       284807
V12       284807
V13       284807
V14       284807
V15       284807
V16       284807
V17       284807
V18       284807
V19       284807
V20       284807
V21       284807
V22       284807
V23       284807
V24       284807
V25       284807
V26       284807
V27       284807
V28       284807
Amount    284807
Class     284807
dtype: int64

In [15]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [16]:
### Independent and dependent features
x=df.drop("Class", axis=1)
y=df.Class

#### Cross validation like KFold and Hyperparameter tuning

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV


In [18]:
log_class = LogisticRegression()
grid = {'C':10.0 **np.arange(-2,3), 'penalty':['l1', 'l2']}
cv=KFold(n_splits=5, random_state = None,shuffle=False)

In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.7)

In [20]:
clf=GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(x_train, y_train)

C:\Users\Rambabu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Rambabu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Rambabu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Rambabu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueErro

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [21]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[198908    107]
 [   132    218]]
0.9988011937902842
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199015
           1       0.67      0.62      0.65       350

    accuracy                           1.00    199365
   macro avg       0.84      0.81      0.82    199365
weighted avg       1.00      1.00      1.00    199365



In [22]:
class_weight=dict({0:1, 1:100})

In [23]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [24]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[199004     11]
 [   101    249]]
0.9994382163368696
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199015
           1       0.96      0.71      0.82       350

    accuracy                           1.00    199365
   macro avg       0.98      0.86      0.91    199365
weighted avg       1.00      1.00      1.00    199365



#### Under Sampling

In [25]:
y_train.value_counts()                              

0    85300
1      142
Name: Class, dtype: int64

In [31]:
from collections import Counter
# from imblearn.under_sampling import NearMiss
from imblearn.under_sampling import RandomUnderSampler  

under_sampler = RandomUnderSampler(0.5)
x_train_rus, y_train_rus = under_sampler.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_rus)))

The number of classes before fit Counter({0: 85300, 1: 142})
The number of classes after fit Counter({0: 284, 1: 142})


C:\Users\Rambabu\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train_rus,y_train_rus)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [28]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[197440   1575]
 [    51    299]]
0.9918441050334813
              precision    recall  f1-score   support

           0       1.00      0.99      1.00    199015
           1       0.16      0.85      0.27       350

    accuracy                           0.99    199365
   macro avg       0.58      0.92      0.63    199365
weighted avg       1.00      0.99      0.99    199365



### Over Sampling

In [35]:
from imblearn.over_sampling import RandomOverSampler
over_sampler = RandomOverSampler(0.75)
x_train_ros, y_train_ros = over_sampler.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ros)))


C:\Users\Rambabu\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classes before fit Counter({0: 85300, 1: 142})
The number of classes after fit Counter({0: 85300, 1: 63975})


In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train_ros,y_train_ros)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [37]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[199000     15]
 [   107    243]]
0.9993880570812329
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199015
           1       0.94      0.69      0.80       350

    accuracy                           1.00    199365
   macro avg       0.97      0.85      0.90    199365
weighted avg       1.00      1.00      1.00    199365



### SMOTETomek

In [34]:
from imblearn.combine import SMOTETomek

In [39]:
st=SMOTETomek(0.75)
x_train_st,y_train_st=st.fit_resample(x_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_st)))

The number of classes before fit Counter({0: 85300, 1: 142})
The number of classes after fit Counter({0: 84616, 1: 63291})


In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train_st,y_train_st)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [42]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[198975     40]
 [    93    257]]
0.9993328819000326
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199015
           1       0.87      0.73      0.79       350

    accuracy                           1.00    199365
   macro avg       0.93      0.87      0.90    199365
weighted avg       1.00      1.00      1.00    199365



### Ensemble Techinique

In [43]:
from imblearn.ensemble import EasyEnsembleClassifier

In [48]:
easy=EasyEnsembleClassifier()
easy.fit(x_train,y_train)

EasyEnsembleClassifier()

In [49]:
y_pred = easy.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[191798   7233]
 [    28    306]]
0.9635793644822311
              precision    recall  f1-score   support

           0       1.00      0.96      0.98    199031
           1       0.04      0.92      0.08       334

    accuracy                           0.96    199365
   macro avg       0.52      0.94      0.53    199365
weighted avg       1.00      0.96      0.98    199365

